---
title: "Ingredient Analysis"
author: "Victor Nguyen"
date: "2022/11/07 - 2022/11/"
output:
    pdf_document:
        toc: true
    html_document:
        toc: true
        toc_float: true
---

```{r setup, include=FALSE}
# Set options
knitr::opts_chunk$set(
    echo=FALSE,
    warning=FALSE,
    message=FALSE,
    fig.align='center'
)
options(digits=5)

# Import libraries
library(tidyverse)
library(ggplot2)
library(gridExtra)
library(RColorBrewer)
```

# Data

## Data Processing

```{r}
# Read in data
ingredients <- read_csv('ingredients.csv')
ingredients <- ingredients %>%
    filter(!str_detect(Category, '^Vitamin D'))
ingredients$Category <- as.factor(ingredients$Category)
ingredients <- ingredients %>%
    rename_with(~gsub(' ', '', .x)) %>%
    rename(Data.Vitamins.VitaminA=`Data.Vitamins.VitaminA-RAE`)
```

# Temporary

```{r include=FALSE}
unique(ingredients$Category)
```

```{r}
groups <- read_csv('category_broad.csv')
broad_cat <- character(0)
for (c in ingredients$Category) {
    u <- FALSE
    for (g in 1:ncol(groups)) {
        if (c %in% groups[[g]]) {
            broad_cat[length(broad_cat) + 1] <- colnames(groups)[g]
            u <- TRUE
            break
        }
    }
    # if (!u) {
    #     broad_cat[length(broad_cat) + 1] <- NA
    #     print(c)
    # }
}
ingredients$Category.Broad <- as.factor(broad_cat)
```

```{r}
ingredients$Data.Vitamins.TotalVitamin <- ingredients$Data.Vitamins.VitaminA +
    ingredients$Data.Vitamins.VitaminB12 +
    ingredients$Data.Vitamins.VitaminB6 * 1000 +
    ingredients$Data.Vitamins.VitaminC * 1000 +
    ingredients$Data.Vitamins.VitaminE * 1000 +
    ingredients$Data.Vitamins.VitaminK
```

```{r}
b12_median <- median(ingredients$Data.Vitamins.VitaminB12)
lvls <- c("Less than 1", "Between 1 and 2", "Between 2 and 3", "Greater than 3")
b12_groups <- character(0)
add_b12 <- function(x) {
    if (x < 1)
        label <- lvls[1]
    else if (x < 2)
        label <- lvls[2]
    else if (x <= 3)
        label <- lvls[3]
    else
        label <- lvls[4]
    return(label)
}
for (item in ingredients$Data.Vitamins.VitaminB12) {
    b12_groups[length(b12_groups) + 1] <- add_b12(item)
}
b12_groups <- factor(b12_groups, levels=lvls)
ingredients$Data.Vitamins.VitaminB12.Group <- b12_groups
```

```{r}
ingredients <- ingredients %>%
    relocate(Category.Broad, .before=Category) %>%
    relocate(Data.Vitamins.VitaminB12.Group, .after=Data.Vitamins.VitaminB12)

plt <- ggplot(ingredients)
```

```{r fig.width=4, fig.height=4}
b12 <- plt +
    geom_histogram(
        aes(Data.Vitamins.VitaminB12),
        color='black',
        fill='#c94f47'
    ) +
    labs(
        title='Distribution of Vitamin B12',
        x='Vitamin B12 (mcg)',
        y='Frequency',
    ) +
    theme_bw()

b6 <- plt +
    geom_histogram(
        aes(Data.Vitamins.VitaminB6),
        color='black',
        fill='#4abd68'
    ) +
    labs(
        title='Distribution of Vitamin B6',
        x='Vitamin B6 (mg)',
        y='Frequency',
    ) +
    theme_bw()

total_vitamin <- plt +
    geom_histogram(
        aes(Data.Vitamins.TotalVitamin),
        color='black',
        fill='#ae45ba'
    ) +
    labs(
        title='Distribution of Vitamin B12',
        x='Vitamin B12 (mcg)',
        y='Frequency',
    ) +
    theme_bw()

copper <- plt +
    geom_histogram(
        aes(Data.MajorMinerals.Copper),
        color='black',
        fill='#c37f12'
    ) +
    labs(
        title='Distribution of copper',
        x='Copper (mg)',
        y='Frequency',
    ) +
    theme_bw()

zinc <- plt +
    geom_histogram(
        aes(Data.MajorMinerals.Zinc),
        color='black',
        fill='#9c9c9c'
    ) +
    labs(
        title='Distribution of zinc',
        x='Zinc (mg)',
        y='Frequency',
    ) +
    theme_bw()

water <- plt +
    geom_histogram(
        aes(Data.Water),
        color='black',
        fill='#9ed8f0'
    ) +
    labs(
        title='Distribution of water',
        x='Water (g)',
        y='Frequency',
    ) +
    theme_bw()

total_lipid <- plt +
    geom_histogram(
        aes(Data.Fat.TotalLipid),
        color='black',
        fill='#e8c433'
    ) +
    labs(
        title='Distribution of total lipid',
        x='Total Lipid (g)',
        y='Frequency',
    ) +
    theme_bw()

fiber <- plt +
    geom_histogram(
        aes(Data.Fiber),
        color='black',
        fill='#7a5225'
    ) +
    labs(
        title='Distribution of fiber',
        x='Fiber (g)',
        y='Frequency',
    ) +
    theme_bw()

grid.arrange(b12, b6, total_vitamin, copper, zinc, water, total_lipid, fiber, nrow=4, ncol=2)
```

```{r}
plt +
    geom_bar(
        aes(x=Data.Vitamins.VitaminB12.Group, fill=Category.Broad),
        position='dodge',
        color='black'
    ) +
    scale_fill_brewer(palette='Set3') +
    labs(
        title='',
        x='Vitamin B12 Group',
        y='Frequency',
        fill='Broad Category'
    ) +
    theme_bw()
```

```{r}
b12_vs_copper <- plt +
    geom_point(aes(x=Data.MajorMinerals.Copper, y=Data.Vitamins.VitaminB12)) +
    labs(
        x='',
        y='Vitamin B12 (mcg)',
        title='Vitamin B12 vs. copper'
    ) +
    theme_bw()

b12_vs_zinc <- plt +
    geom_point(aes(x=Data.MajorMinerals.Zinc, y=Data.Vitamins.VitaminB12)) +
    labs(
        x='',
        y='',
        title='Vitamin B12 vs. zinc'
    ) +
    theme_bw()

b6_vs_copper <- plt +
    geom_point(aes(x=Data.MajorMinerals.Copper, y=Data.Vitamins.VitaminB6)) +
    labs(
        x='Copper (mg)',
        y='Vitamin B6 (mg)',
        title='Vitamin B6 vs. copper'
    ) +
    theme_bw()

b6_vs_zinc <- plt +
    geom_point(aes(x=Data.MajorMinerals.Zinc, y=Data.Vitamins.VitaminB6)) +
    labs(
        x='Zinc (mg)',
        y='',
        title='Vitamin B6 vs. zinc'
    ) +
    theme_bw()

grid.arrange(b12_vs_copper, b12_vs_zinc, b6_vs_copper, b6_vs_zinc, nrow=2, ncol=2)
```

```{r}
fat_vs_water <- plt +
    geom_point(aes(x=Data.Water, y=Data.Fat.TotalLipid)) +
    labs(
        title='Total lipid vs. water',
        x='Water (g)',
        y='Total Lipid (g)'
    ) +
    theme_bw()

fiber_vs_water <- plt +
    geom_point(aes(x=Data.Water, y=Data.Fiber)) +
    labs(
        title='Fiber vs. water',
        x='Water (g)',
        y='Fiber (g)'
    ) +
    theme_bw()

grid.arrange(fat_vs_water, fiber_vs_water, nrow=1, ncol=2)

plt +
    geom_point(aes(x=Data.Fiber, y=Data.Fat.TotalLipid)) +
    labs(
        title='Total lipid vs. fiber',
        x='Total Lipid (g)',
        y='Fiber (g)'
    ) +
    theme_bw()
```

```{r}
plt +
    geom_boxplot(aes(x=Data.Vitamins.TotalVitamin, fill=Category.Broad)) +
    scale_fill_brewer(palette='Set3') +
    xlim(0, 6e4) +
    labs(
        title='Distributions of total vitamin for each broad category',
        x='Total Vitamin (mcg)',
        fill='Broad Category'
    ) +
    theme_bw() +
    theme(
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank()
    )
```
# Vitamins in Relation to Minerals

## Vitamin B12

## Vitamin B6

# Water Content

## Water vs. Lipids

## Water vs. Fiber

# Vitamins